version: "3.7"

services:
  api:
    restart: on-failure
    build:
      context: ../
      dockerfile: docker/api.Dockerfile
    env_file:
      - .env
    ports:
      - "${API_PORT}:${API_PORT}"
    command: "uvicorn flights_api.api_endpoints:app --host 0.0.0.0 --port ${API_PORT}"
    depends_on:
      - postgres

  postgres:
    restart: on-failure
    image: "postgres:14.5"
    command: postgres -c 'max_connections=50'
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_DB: "${POSTGRES_DB}"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${POSTGRES_USER}" ]
      interval: 5s
      retries: 5

  tests:
    build:
      context: ../
      dockerfile: docker/tests.Dockerfile
    env_file:
      - .env
    command: pytest -m "not sample_fixtures" tests/integration/
    depends_on:
      - api
